[build-system]
requires = ["setuptools", "wheel", "logging"]
build-backend = "setuptools.build_meta"

[project]
name = "local_db"
version = "1.2.0"
description = "package for handling local database files and data"
authors = [{name = "Elias Rodkey", email = "elias.rodkey@gmail.com"}]
license = "MIT"
dependencies = ["requests", "numpy", "sqlalchemy", "loggers", "pandas"]  # List your package dependencies here